Update for Cake 5.x
tyrellsys/cakephp-validator pull request #1
Opened 2024-09-02 09:59 UTC by Ridzuan94

Improvement for CakePHP5

2024-09-02 10:05 UTC, Ridzuan94 commented on src/Validation/Validator.php
> +    }
Fix indentation when running composer cs-fix.
Next, follow the argument data type based on the CakePHP5 Validator.
Refer: https://github.com/cakephp/validation/blob/5.x/Validator.php

2024-09-02 10:07 UTC, Ridzuan94 commented on tests/TestCase/Validation/ValidatorTest.php
> +            ->array('column')
`Validator::isArray()` is deprecated in CakePHP5. Need to use `Validator::array()` instead.
Refer: https://book.cakephp.org/4/en/appendices/4-5-migration-guide.html#validation

2024-09-02 10:15 UTC, Ridzuan94 commented on tests/TestCase/Validation/ValidatorTest.php
> +            'file' => new UploadedFile('', 0, UPLOAD_ERR_NO_FILE, null, null),
The file attachment already changed from an array to an `UploadedFile` object.
Refer: https://book.cakephp.org/5/en/appendices/5-0-migration-guide.html#http

2025-01-17 03:35 UTC, TABTyrell requested changes
@mtak3

2025-01-17 03:35 UTC, TABTyrell commented on tests/TestCase/Validation/ValidatorTest.php
> -            'notEquals' => 'notEquals',
For `notEquals`, the Validation::comparison() method uses the operator `!=`. 

Currently, the values being compared are `[]` and `1`. With these values, the comparison will always return true. Instead of removing notEquals, why not fix the following line:

https://github.com/Ridzuan94/cakephp-validator/blob/eb3ca1f6482e839e09001e1840939a95a592b7d2/tests/TestCase/Validation/ValidatorTest.php#L266

Ensure that the value being compared is consistent with what is used for validation in this line:

https://github.com/Ridzuan94/cakephp-validator/blob/eb3ca1f6482e839e09001e1840939a95a592b7d2/tests/TestCase/Validation/ValidatorTest.php#L312

This way, it will not be necessary to remove notEquals from the errors column. Please check.

2025-03-14 04:19 UTC, Ridzuan94 commented on tests/TestCase/Validation/ValidatorTest.php
> -            'notEquals' => 'notEquals',
@TABTyrell 
Understood. For this fixed at 12d461cf66b80d571777302a9540fcbb2162f721.
Already ran composer test and it worked as expected.
Thank you for the advice given appreciate it. 🙏

2025-04-21 03:38 UTC, merged